# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hypersomnia newspaper
email: patryk.czachurski@gmail.com
description: Daily record of progress and new features.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hypersomnia.pl" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  geneotech
img_dir:  

# Build settings
markdown: kramdown
paginate: 6
paginate_path: "page:num"
gems: [jekyll-paginate]